### PR TITLE
Makefile: Make go tools ignore go and linter cache dirs

### PR DESCRIPTION
**Pull request by orelmisan**
Currently, if the linter cache directory exists, the `go mod tidy` command fails, because it doesn't have permissions to read it.

Add an underscore as a prefix to the `go-cache` and `linter-cache` directories, so the `go mod tidy` command will ignore them[1].

Apply to `.gitignore` and `.dockerignore` as well.

[1] https://pkg.go.dev/cmd/go#hdr-Package_lists_and_patterns

Signed-off-by: Orel Misan <omisan@redhat.com>

### CODE REVIEW

**Comment by RamLavi** [comment]
strange, it doesn't happen in case..

**Comment by orelmisan** [comment]
[Change](https://github.com/kiagnose/kubevirt-rt-checkup/compare/4f86ea20e30ba683bb0802477d3f1202cb73affe..b15308d4c1b41250fe00be5ea1445b74e5790f39): Updated commit message.

**Comment by RamLavi** [comment]
Alternative suggestion:
why do you use the cache for the vendor target makefile? it's not so time consuming...

**Comment by orelmisan** [comment]
> Alternative suggestion: why do you use the cache for the vendor target makefile? it's not so time consuming...

This is a different discussion.
This PR is trying to make `go mod tidy` ignore the cache directories so it won't try to operate on them.

**Comment by RamLavi** [comment]
> > Alternative suggestion: why do you use the cache for the vendor target makefile? it's not so time consuming...
> 
> This is a different discussion. This PR is trying to make `go mod tidy` ignore the cache directories so it won't try to operate on them.

fair enough

**Review by RamLavi — APPROVED** [review]
/lgtm

**Pull request merged**
