### PR TITLE
Align the VMI spec

### PR DESCRIPTION
**Pull request by orelmisan**
Align the VMI spec according to [1].
Use `Domain.CPU` and `Domain.Memory` instead of the pod oriented `vmi.Spec.Domain.Resources`.

[1] https://access.redhat.com/solutions/7007632

Example config:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    cpu-load-balancing.crio.io: disable
    cpu-quota.crio.io: disable
    irq-load-balancing.crio.io: disable
  name: rt-vmi-7x7pz
spec:
  domain:
    cpu:
      sockets: 1
      cores: 3
      threads: 1
      dedicatedCpuPlacement: true
      isolateEmulatorThread: true
      model: host-passthrough
      numa:
        guestMappingPassthrough: {}
      realtime: {}
    devices:
      autoattachGraphicsDevice: false
      autoattachMemBalloon: false
      autoattachSerialConsole: true
      disks:
        - disk:
            bus: virtio
          name: rootdisk
        - disk:
            bus: virtio
          name: cloudinitdisk
    ioThreadsPolicy: auto
    memory:
      guest: 4Gi
      hugepages:
        pageSize: 1Gi
  terminationGracePeriodSeconds: 0
  volumes:
    - containerDisk:
        image: 'quay.io/kiagnose/kubevirt-realtime-checkup-vm:main'
      name: rootdisk
    - cloudInitNoCloud:
        userData: |-
          #cloud-config
          password: redhat
          chpasswd:
            expire: false
          user: user
      name: cloudinitdisk
```

~~Depends on PR #33, please skip the first two commits.~~

### CODE REVIEW

**Comment by orelmisan** [comment]
Tested against an OpenShift Virtualization 4.15 cluster.

**Review by RamLavi — COMMENTED** [review]
could you mention the https://access.redhat.com/solutions/7007632 link on all the commits that do changes regarding it?

**Comment by RamLavi** [comment]
I think `cpu-load-balancing.crio.io` annotation is not needed according to https://access.redhat.com/solutions/7007632, could you remove it?

**Comment by orelmisan** [comment]
> could you mention the https://access.redhat.com/solutions/7007632 link on all the commits that do changes regarding it?

Done [here](https://github.com/kiagnose/kubevirt-realtime-checkup/compare/0f8b4d6bdd63f16370655fea4b09b9ee79feba7c..cc6e88c1cc8a44cf6012467d37b127bcb79188d4).

**Comment by orelmisan** [comment]
> I think `cpu-load-balancing.crio.io` annotation is not needed according to https://access.redhat.com/solutions/7007632, could you remove it?

It is indeed not there.
@matosatti do we still need to keep the three CRI-O annotations?

**Comment by RamLavi** [comment]
@orelmisan I think we also need to add: `spec.domain.cpu.realtime: {}`
(Or perhaps I missed it?)

**Comment by orelmisan** [comment]
> @orelmisan I think we also need to add: `spec.domain.cpu.realtime: {}`

We have it, please see the example output in the PR description.

**Comment by matosatti** [comment]
> > I think `cpu-load-balancing.crio.io` annotation is not needed according to https://access.redhat.com/solutions/7007632, could you remove it?
> 
> It is indeed not there. @matosatti do we still need to keep the three CRI-O annotations?
It is, see comment 3 of:
https://bugzilla.redhat.com/show_bug.cgi?id=2185411#c3

**Review by RamLavi — APPROVED** [review]
/lgtm

**Pull request merged**
