### PR TITLE
client: Update kubevirt.io/client-go to v1.0.0

### PR DESCRIPTION
**Pull request by orelmisan**
Currently, we are using kubevirt.io/client-go@v0.58.0.

Update to v1.0.0 in order to:
1. Take advantage of context.Context parameter that was added to VMI methods.
2. Eliminate the following warning from the checkup's logs:
```
W0702 08:56:11.138067 1 warnings.go:70] kubevirt.io/v1alpha3
is now deprecated and will be removed in a future release.
```

Pin K8s deps to v0.26.3 to match definitions set in kubevirt.io/client-go.

### CODE REVIEW

**Review by RamLavi — COMMENTED** [review]
could ypou also mention in the commit desc that ou are pinning to kubernetes-0.26.3 vendor?

**Comment by orelmisan** [comment]
> could ypou also mention in the commit desc that ou are pinning to kubernetes-0.26.3 vendor?

There was already a pin to an older version.
This PR is similar to https://github.com/kiagnose/kubevirt-dpdk-checkup/pull/114

**Comment by RamLavi** [comment]
> > could ypou also mention in the commit desc that ou are pinning to kubernetes-0.26.3 vendor?
> 
> There was already a pin to an older version. This PR is similar to [kiagnose/kubevirt-dpdk-checkup#114](https://github.com/kiagnose/kubevirt-dpdk-checkup/pull/114)

It is. I'm just saying that it's worth mentioning. won't insist on it though.

**Comment by orelmisan** [comment]
Updated commit message.

**Review by RamLavi — APPROVED** [review]
/lgtm

**Pull request merged**
